services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - wp-network

  php:
    build:
      context: ./docker/php
    restart: always
    ports:
      - "9001:9000"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb
    networks:
      - wp-network

  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - "./data/db:/var/lib/mysql"
    networks:
      - wp-network

  adminer:
    image: shyim/adminerevo:latest
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - mariadb
    networks:
      - wp-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - wp-network

networks:
  wp-network:
